import:
  - ~/.config/alacritty/dark_gruvbox_theme.yaml
font:
  normal:
    family: Fira Code
    style:  Bold
  bold:
    family: Fira Code
    style:  Bold
  italic:
    family: Fira Code
    style:  Bold Italic
  bold_italic:
    family: Fira Code
    style:  Bold Italic
  size: 10
theme: Gruvbox-Dark
window:
  padding:
    x: 10
    y: 10
