items:
  - colors:
      name: 3024 (dark)
      author: Chris Kempson
      primary:
        background: "#090300"
        foreground: "#a5a2a2"
      cursor:
        text:   "#090300"
        cursor: "#a5a2a2"
      normal:
        black:    "#090300"
        red:      "#db2d20"
        green:    "#01a252"
        yellow:   "#fded02"
        blue:     "#01a0e4"
        magenta:  "#a16a94"
        cyan:     "#b5e4f4"
        white:    "#a5a2a2"
      bright:
        black:    "#5c5855"
        red:      "#db2d20"
        green:    "#01a252"
        yellow:   "#fded02"
        blue:     "#01a0e4"
        magenta:  "#a16a94"
        cyan:     "#b5e4f4"
        white:    "#f7f7f7"
  #- theme: 3024.dark
colors:
  primary:
    background: "#282828"
    # hc background:  "#1d2021"
    foreground: "#ebdbb2"
    # hc foreground:  "#32302f"
  normal:
    black:    "#282828"
    red:      "#cc241d"
    green:    "#98971a"
    yellow:   "#d79921"
    blue:     "#458588"
    magenta:  "#b16286"
    cyan:     "#689d6a"
    white:    "#a89984"
  bright:
    black:    "#928374"
    red:      "#fb4934"
    green:    "#b8bb26"
    yellow:   "#fabd2f"
    blue:     "#83a598"
    magenta:  "#d3869b"
    cyan:     "#8ec07c"
    white:    "#ebdbb2"
